UPLOAD_DATA_DIRECTORY="uploaded_data"
CLEAN_DATA_DIRECTORY="cleaned_data"
TEMP_DIRECTORY="temp_data"
PERSIST_DIRECTORY="stored_vector_db"
CACHE_DIRECTORY="__pycache__"
BASE_URL="https://entiovi.com"
URL_FILE_NAME="urls_file.txt"
UPLOADED_FILE_NAMES="uploaded_file.txt"
OPENAI_EMBEDDING_MODEL="text-embedding-ada-002"
OPENAI_LLM_MODEL="gpt-3.5-turbo-0613"
OPENAI_API_KEY="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"

